FROM python:3.9-slim
WORKDIR /app

# Copy requirements from backend folder
COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend source code
COPY backend/ .

EXPOSE 8083
CMD ["python", "app.py"]
